### ISSUE TITLE
How to save a map after creating it

### ISSUE THREAD

**Issue by DongDong-Juice** [aserbremen/Multi-Robot-Graph-SLAM#1]
I have modified the VLP32C to be usable using your slam and am now using it without any problems.
usage environment
Ubuntu 22.04LTS
ROS version
humble
Instructions to use
ros2 run nav2_map_server map_saver_server -f /path/to
expected behavior
Map saved successfully
actual action
Map save failed

I want to save a map, can you tell me how?

**Comment by aserbremen** [comment]
I am not familiar with the nav2_map_server node and I am not sure whether this SLAM is compatible with it yet. However, you can save the map to a .pcd file using the [save map service](https://github.com/aserbremen/mrg_slam_msgs/blob/main/srv/SaveMap.srv). I updated the API and fixed some bugs concerning the saving of maps and graph. 

You need to `git pull` the latest commits in of [mrg_slam](https://github.com/aserbremen/mrg_slam) and [mrg_slam_msgs](https://github.com/aserbremen/mrg_slam_msgs) in your workspace. 

## saving the map (3D point cloud)

Then you can call the save map service as follows:

`ros2 service call /<model_namespace>/mrg_slam/save_map mrg_slam_msgs/srv/SaveMap "{file_path: /my/file_path/map.pcd}"`

This will save the `.pcd` file which you can inspect with e.g. `pcl_viewer /my/file_path/map.pcd`. 

You can additionally provide the desired point cloud resolution in meters. A voxel grid filter will be applied with the given resolution.  

`ros2 service call /<model_namespace>/mrg_slam/save_map mrg_slam_msgs/srv/SaveMap "{file_path: /my/file_path/map.pcd, resolution: 0.05}"`

## saving the graph

You can additionally save the graph containing the "regular" g20 graph and additional detailed information about keyframes and edges. 

`ros2 service call /<model_namespace>/mrg_slam/save_graph mrg_slam_msgs/srv/SaveGraph "{directory: /path/to/directory}"`

You will end up with the following folder structure:

```
├── edges
│   ├── 000000.txt
│   ├── 000001.txt
│   ├── 000002.txt
│   ├── 000003.txt
│   ├── 000004.txt
│   ├── 000005.txt
│   ├── ...
├── g2o
│   ├── graph.g2o
│   ├── graph.g2o.kernels
│   └── special_nodes.csv
├── keyframes
│   ├── 000000.pcd
│   ├── 000000.txt
│   ├── 000001.pcd
│   ├── 000001.txt
│   ├── 000002.pcd
│   ├── 000002.txt
│   ├── 000003.pcd
│   ├── 000003.txt
│   ├── ...
├── network_stats.txt
└── timing_stats.txt
```

Each edge is represented with a `.txt`. Each keyframe is represented by `.txt` file and its associated point cloud with the respective `.pcd` file.

**Comment by DongDong-Juice** [comment]
Thank you, I will try the method you suggested!
If a similar error occurs, I will leave an issue. Or, I'll open a new issue and ask a question!
Good luck for your future!

**Comment by DongDong-Juice** [comment]
ros2 service call /atlas/mrg_slam/save_map mrg_slam_msgs/srv/SaveMap "{file_path: '/path/to/save/map.pcd, resolution: 0.1}"
->
ros2 service call /atlas/mrg_slam/save_map mrg_slam_msgs/srv/SaveMap "{file_path: '/path/to/save/map.pcd' , resolution: 0.1}"
' addition

readme I think I need to fix it 
@aserbremen

**Comment by aserbremen** [comment]
thanks i updated the readme
