### ISSUE TITLE
slam infeasibility problem

### ISSUE THREAD

**Issue by DongDong-Juice** [aserbremen/Multi-Robot-Graph-SLAM#2]
hi @aserbremen 
After receiving information about saving the map
I encountered an issue while updating and re-running Git to test saving the map.
The problem I'm facing is that the slam isn't working properly.
Can you please tell me a solution to this problem? Or I just want to know why the problem occurs
I also completely deleted Git and cloned the latest commit.

**environment**
Connect to turtlebot4 discovery server

**operating system**
linux

**Run ros2 version**
ros2 humble

**What i want**
velodyne 3d slam into cartography

**actual action**
not executable

Below is the terminal output I encountered.
I couldn't include the log because I didn't know what to give. If you need more, please tell me more details.

---------------------------------------------------------------------------------------

ros2 launch mrg_slam mrg_slam.launch.py model_namespace:=atlas x:=0.0 y:=0.0 z:=0.0 roll:=0.0 pitch:=0.0 yaw:=0.0
[INFO] [launch]: All log files can be found below /home/dong/.ros/log/2024-05-20-16-09-43-961898-dong-Vostro-15-5510-21420
[INFO] [launch]: Default logging verbosity is set to INFO
Loaded config file: /home/dong/3d_slam/Multi-Robot-Graph-SLAM/install/mrg_slam/share/mrg_slam/config/mrg_slam.yaml
######## shared_params ########
model_namespace: atlas
use_sim_time: true
points_topic: /velodyne_points
imu_topic: /imu/data

######## static_transform_params ########
lidar2base_x: 0.0
lidar2base_y: 0.0
lidar2base_z: 0.0
lidar2base_roll: 0.0
lidar2base_pitch: 0.0
lidar2base_yaw: 0.0
base_frame_id: base_link
lidar_frame_id: velodyne

######## map2robotmap_publisher_params ########
enable_map2robotmap_publisher: true
map2robotmap_x: 0.0
map2robotmap_y: 0.0
map2robotmap_z: 0.0
map2robotmap_roll: 0.0
map2robotmap_pitch: 0.0
map2robotmap_yaw: 0.0
map2robotmap_frame_id: map
map2robotmap_child_frame_id: map

######## clock_publisher_ros2_params ########
imu_topic: /gpsimu_driver/imu_data

######## velodyne_params ########
enable_velodyne: false
velodyne_driver:
  driver_node_params_file: VLP16-velodyne_driver_node-params.yaml
  frame_id: velodyne
velodyne_transform:
  transform_node_params_file: VLP16-velodyne_transform_node-params.yaml
  calibration: VLP16db.yaml
  fixed_frame: velodyne

######## prefiltering_params ########
enable_prefiltering: true
downsample_method: VOXELGRID
downsample_resolution: 0.1
outlier_removal_method: RADIUS
statistical_mean_k: 30
statistical_stddev: 1.2
radius_radius: 0.5
radius_min_neighbors: 2
use_distance_filter: true
distance_near_thresh: 0.1
distance_far_thresh: 100.0
scan_period: 0.1
deskewing: false
base_link_frame: base_link

######## scan_matching_odometry_params ########
enable_scan_matching_odometry: true
enable_odom_to_file: true
points_topic: /velodyne_points
odom_frame_id: odom
robot_odom_frame_id: robot_odom
keyframe_delta_trans: 1.0
keyframe_delta_angle: 1.0
keyframe_delta_time: 10000.0
transform_thresholding: false
max_acceptable_trans: 1.0
max_acceptable_angle: 1.0
enable_robot_odometry_init_guess: false
enable_imu_frontend: false
downsample_method: NONE
downsample_resolution: 0.1
registration_method: FAST_GICP
reg_num_threads: 0
reg_transformation_epsilon: 0.1
reg_maximum_iterations: 64
reg_max_correspondence_distance: 2.0
reg_max_optimizer_iterations: 20
reg_use_reciprocal_correspondences: false
reg_correspondence_randomness: 20
reg_resolution: 1.0
reg_nn_search_method: DIRECT7

######## floor_detection_params ########
enable_floor_detection: false
tilt_deg: 0.0
sensor_height: 2.0
height_clip_range: 1.0
floor_pts_thresh: 512
floor_normal_thresh: 10.0
use_normal_filtering: true
normal_filter_thresh: 20.0
points_topic: /velodyne_points

######## mrg_slam_params ########
enable_graph_slam: true
own_name: atlas
multi_robot_names:
- atlas
- bestla
robot_remove_points_radius: 2.0
x: 0.0
y: 0.0
z: 0.0
roll: 0.0
pitch: 0.0
yaw: 0.0
init_pose:
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
- 0.0
init_pose_topic: NONE
map_frame_id: map
odom_frame_id: odom
g2o_solver_type: lm_var_cholmod
g2o_solver_num_iterations: 512
g2o_verbose: false
enable_gps: false
enable_imu_acceleration: false
enable_imu_orientation: false
max_keyframes_per_update: 10000
keyframe_delta_trans: 1.0
keyframe_delta_angle: 1.0
fix_first_node: true
fix_first_node_adaptive: false
fix_first_node_stddev:
- 0.5
- 0.5
- 0.5
- 0.0872665
- 0.0872665
- 0.0872665
distance_thresh: 15.0
accum_distance_thresh: 25.0
min_edge_interval: 15.0
fitness_score_max_range: .inf
fitness_score_thresh: 2.5
use_planar_registration_guess: false
loop_closure_edge_robust_kernel: Huber
loop_closure_edge_robust_kernel_size: 1.0
use_loop_closure_consistency_check: true
loop_closure_consistency_max_delta_trans: 0.3
loop_closure_consistency_max_delta_angle: 3.0
registration_method: FAST_GICP
reg_num_threads: 0
reg_transformation_epsilon: 0.1
reg_maximum_iterations: 64
reg_max_correspondence_distance: 2.0
reg_max_optimizer_iterations: 20
reg_use_reciprocal_correspondences: false
reg_correspondence_randomness: 20
reg_resolution: 1.0
reg_nn_search_method: DIRECT7
gps_edge_robust_kernel: NONE
gps_edge_robust_kernel_size: 1.0
gps_edge_stddev_xy: 20.0
gps_edge_stddev_z: 5.0
imu_orientation_edge_robust_kernel: NONE
imu_orientation_edge_stddev: 1.0
imu_acceleration_edge_robust_kernel: NONE
imu_acceleration_edge_stddev: 1.0
floor_edge_robust_kernel: NONE
floor_edge_stddev: 10.0
odometry_edge_robust_kernel: NONE
odometry_edge_robust_kernel_size: 1.0
use_const_inf_matrix: false
const_stddev_x: 0.5
const_stddev_q: 0.1
var_gain_a: 20.0
min_stddev_x: 0.1
max_stddev_x: 5.0
min_stddev_q: 0.05
max_stddev_q: 0.2
graph_request_min_accum_dist: 2.0
graph_request_max_robot_dist: 50.0
graph_request_min_time_delay: 2.0
graph_exchange_mode: PATH_PROXIMITY
graph_update_interval: 3.0
map_cloud_update_interval: 2.0
map_cloud_resolution: 0.1
save_graph: false
result_dir: ''

######## map2odom_publisher_ros2 remappings ########
/mrg_slam/odom2pub -> /atlas/mrg_slam/odom2pub

######## prefiltering_component remappings ########
/imu/data -> /atlas/imu/data
/velodyne_points -> /atlas/velodyne_points
/prefiltering/filtered_points -> /atlas/prefiltering/filtered_points
/prefiltering/colored_points -> /atlas/prefiltering/colored_points

######## scan_matching_odometry_component remappings ########
/points_topic -> /atlas/velodyne_points
/filtered_points -> /atlas/prefiltering/filtered_points
/scan_matching_odometry/transform -> /atlas/scan_matching_odometry/transform
/scan_matching_odometry/read_until -> /atlas/scan_matching_odometry/read_until
/scan_matching_odometry/status -> /atlas/scan_matching_odometry/status
/scan_matching_odometry/odom -> /atlas/scan_matching_odometry/odom
/scan_matching_odometry/aligned_points -> /atlas/scan_matching_odometry/aligned_points

######## floor_detection_component remappings ########
/points_topic -> /atlas/velodyne_points
/filtered_points -> /atlas/prefiltering/filtered_points
/floor_detection/floor_coeffs -> /atlas/floor_detection/floor_coeffs
/floor_detection/floor_filtered_points -> /atlas/floor_detection/floor_filtered_points
/floor_detection/read_until -> /atlas/floor_detection/read_until
/floor_detection/floor_points -> /atlas/floor_detection/floor_points

######## mrg_slam_component remappings ########
/imu/data -> /imu/data
/filtered_points -> /atlas/prefiltering/filtered_points
/odom -> /atlas/scan_matching_odometry/odom
/floor_coeffs -> /atlas/floor_detection/floor_coeffs
/mrg_slam/map_points -> /atlas/mrg_slam/map_points
/mrg_slam/markers -> /atlas/mrg_slam/markers
/mrg_slam/markers_node_names -> /atlas/mrg_slam/markers_node_names
/mrg_slam/markers_covariance -> /atlas/mrg_slam/markers_covariance
/mrg_slam/odom2pub -> /atlas/mrg_slam/odom2pub
/mrg_slam/read_until -> /atlas/mrg_slam/read_until
/mrg_slam/others_poses -> /atlas/mrg_slam/others_poses
/mrg_slam/publish_graph -> /atlas/mrg_slam/publish_graph
/mrg_slam/slam_status -> /atlas/mrg_slam/slam_status
/mrg_slam/save_graph -> /atlas/mrg_slam/save_graph
/mrg_slam/save_map -> /atlas/mrg_slam/save_map
/mrg_slam/get_map -> /atlas/mrg_slam/get_map
/mrg_slam/get_graph_estimate -> /atlas/mrg_slam/get_graph_estimate
/mrg_slam/request_graph -> /atlas/mrg_slam/request_graph
/mrg_slam/save_gids -> /atlas/mrg_slam/save_gids
/mrg_slam/get_graph_gids -> /atlas/mrg_slam/get_graph_gids

[INFO] [static_transform_publisher-1]: process started with pid [21439]
[INFO] [static_transform_publisher-2]: process started with pid [21441]
[INFO] [map2odom_publisher_ros2.py-3]: process started with pid [21443]
[INFO] [component_container_mt-4]: process started with pid [21445]
[INFO] [odom_to_file.py-5]: process started with pid [21447]
[static_transform_publisher-1] [WARN] [1716188984.217228001] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-2] [WARN] [1716188984.222629052] []: Old-style arguments are deprecated; see --help for new-style arguments
[static_transform_publisher-1] [INFO] [1716188984.227010454] [atlas.lidar2base_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-1] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-1] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-1] from 'atlas/base_link' to 'atlas/velodyne'
[static_transform_publisher-2] [INFO] [1716188984.237053131] [atlas.map2robotmap_publisher]: Spinning until stopped - publishing transform
[static_transform_publisher-2] translation: ('0.000000', '0.000000', '0.000000')
[static_transform_publisher-2] rotation: ('0.000000', '0.000000', '0.000000', '1.000000')
[static_transform_publisher-2] from 'map' to 'atlas/map'
[component_container_mt-4] [INFO] [1716188987.960190672] [atlas.mrg_slam_container]: Load Library: /home/dong/3d_slam/Multi-Robot-Graph-SLAM/install/mrg_slam/lib/libprefiltering_component.so
[component_container_mt-4] [INFO] [1716188987.971754783] [atlas.mrg_slam_container]: Found class: rclcpp_components::NodeFactoryTemplate<mrg_slam::PrefilteringComponent>
[component_container_mt-4] [INFO] [1716188987.971794409] [atlas.mrg_slam_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<mrg_slam::PrefilteringComponent>
[component_container_mt-4] [INFO] [1716188987.975854164] [atlas.prefiltering_component]: Initializing prefiltering_component...
[component_container_mt-4] downsample: VOXELGRID 0.1
[component_container_mt-4] outlier_removal: RADIUS 0.5 - 2
[component_container_mt-4] [INFO] [1716188987.981537153] [atlas.prefiltering_component]: base_link_frame              atlas/base_link
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/atlas/prefiltering_component' in container 'atlas/mrg_slam_container'
[component_container_mt-4] [INFO] [1716188987.981567180] [atlas.prefiltering_component]: deskewing                    false
[component_container_mt-4] [INFO] [1716188987.981577941] [atlas.prefiltering_component]: distance_far_thresh          100.000000
[component_container_mt-4] [INFO] [1716188987.981584437] [atlas.prefiltering_component]: distance_near_thresh         0.100000
[component_container_mt-4] [INFO] [1716188987.981592736] [atlas.prefiltering_component]: downsample_method            VOXELGRID
[component_container_mt-4] [INFO] [1716188987.981598661] [atlas.prefiltering_component]: downsample_resolution        0.100000
[component_container_mt-4] [INFO] [1716188987.981604161] [atlas.prefiltering_component]: outlier_removal_method       RADIUS
[component_container_mt-4] [INFO] [1716188987.981637052] [atlas.prefiltering_component]: qos_overrides./clock.subscription.depth 1
[component_container_mt-4] [INFO] [1716188987.981644219] [atlas.prefiltering_component]: qos_overrides./clock.subscription.durability volatile
[component_container_mt-4] [INFO] [1716188987.981649868] [atlas.prefiltering_component]: qos_overrides./clock.subscription.history keep_last
[component_container_mt-4] [INFO] [1716188987.981655275] [atlas.prefiltering_component]: qos_overrides./clock.subscription.reliability best_effort
[component_container_mt-4] [INFO] [1716188987.981660770] [atlas.prefiltering_component]: qos_overrides./parameter_events.publisher.depth 1000
[component_container_mt-4] [INFO] [1716188987.981666103] [atlas.prefiltering_component]: qos_overrides./parameter_events.publisher.durability volatile
[component_container_mt-4] [INFO] [1716188987.981671513] [atlas.prefiltering_component]: qos_overrides./parameter_events.publisher.history keep_last
[component_container_mt-4] [INFO] [1716188987.981677210] [atlas.prefiltering_component]: qos_overrides./parameter_events.publisher.reliability reliable
[component_container_mt-4] [INFO] [1716188987.981683395] [atlas.prefiltering_component]: radius_min_neighbors         2
[component_container_mt-4] [INFO] [1716188987.981690228] [atlas.prefiltering_component]: radius_radius                0.500000
[component_container_mt-4] [INFO] [1716188987.981698786] [atlas.prefiltering_component]: scan_period                  0.100000
[component_container_mt-4] [INFO] [1716188987.981706060] [atlas.prefiltering_component]: statistical_mean_k           30
[component_container_mt-4] [INFO] [1716188987.981712142] [atlas.prefiltering_component]: statistical_stddev           1.200000
[component_container_mt-4] [INFO] [1716188987.981717428] [atlas.prefiltering_component]: use_distance_filter          true
[component_container_mt-4] [INFO] [1716188987.981722619] [atlas.prefiltering_component]: use_sim_time                 true
[component_container_mt-4] [INFO] [1716188987.983396499] [atlas.mrg_slam_container]: Load Library: /home/dong/3d_slam/Multi-Robot-Graph-SLAM/install/mrg_slam/lib/libscan_matching_odometry_component.so
[component_container_mt-4] [INFO] [1716188987.985704345] [atlas.mrg_slam_container]: Found class: rclcpp_components::NodeFactoryTemplate<mrg_slam::ScanMatchingOdometryComponent>
[component_container_mt-4] [INFO] [1716188987.985726076] [atlas.mrg_slam_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<mrg_slam::ScanMatchingOdometryComponent>
[component_container_mt-4] [INFO] [1716188987.990032231] [atlas.scan_matching_odometry_component]: Initializing scan_matching_odometry_component...
[component_container_mt-4] downsample: NONE
[component_container_mt-4] registration: FAST_GICP
[component_container_mt-4] [INFO] [1716188988.600666831] [atlas.scan_matching_odometry_component]: downsample_method            NONE
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/atlas/scan_matching_odometry_component' in container 'atlas/mrg_slam_container'
[component_container_mt-4] [INFO] [1716188988.600706250] [atlas.scan_matching_odometry_component]: downsample_resolution        0.100000
[component_container_mt-4] [INFO] [1716188988.600711812] [atlas.scan_matching_odometry_component]: enable_imu_frontend          false
[component_container_mt-4] [INFO] [1716188988.600715486] [atlas.scan_matching_odometry_component]: enable_robot_odometry_init_guess false
[component_container_mt-4] [INFO] [1716188988.600719556] [atlas.scan_matching_odometry_component]: keyframe_delta_angle         1.000000
[component_container_mt-4] [INFO] [1716188988.600724399] [atlas.scan_matching_odometry_component]: keyframe_delta_time          10000.000000
[component_container_mt-4] [INFO] [1716188988.600752762] [atlas.scan_matching_odometry_component]: keyframe_delta_trans         1.000000
[component_container_mt-4] [INFO] [1716188988.600757601] [atlas.scan_matching_odometry_component]: max_acceptable_angle         1.000000
[component_container_mt-4] [INFO] [1716188988.600761376] [atlas.scan_matching_odometry_component]: max_acceptable_trans         1.000000
[component_container_mt-4] [INFO] [1716188988.600765029] [atlas.scan_matching_odometry_component]: odom_frame_id                atlas/odom
[component_container_mt-4] [INFO] [1716188988.600768772] [atlas.scan_matching_odometry_component]: points_topic                 /velodyne_points
[component_container_mt-4] [INFO] [1716188988.600772613] [atlas.scan_matching_odometry_component]: qos_overrides./clock.subscription.depth 1
[component_container_mt-4] [INFO] [1716188988.600780332] [atlas.scan_matching_odometry_component]: qos_overrides./clock.subscription.durability volatile
[component_container_mt-4] [INFO] [1716188988.600784290] [atlas.scan_matching_odometry_component]: qos_overrides./clock.subscription.history keep_last
[component_container_mt-4] [INFO] [1716188988.600787867] [atlas.scan_matching_odometry_component]: qos_overrides./clock.subscription.reliability best_effort
[component_container_mt-4] [INFO] [1716188988.600791723] [atlas.scan_matching_odometry_component]: qos_overrides./parameter_events.publisher.depth 1000
[component_container_mt-4] [INFO] [1716188988.600795416] [atlas.scan_matching_odometry_component]: qos_overrides./parameter_events.publisher.durability volatile
[component_container_mt-4] [INFO] [1716188988.600798844] [atlas.scan_matching_odometry_component]: qos_overrides./parameter_events.publisher.history keep_last
[component_container_mt-4] [INFO] [1716188988.600802334] [atlas.scan_matching_odometry_component]: qos_overrides./parameter_events.publisher.reliability reliable
[component_container_mt-4] [INFO] [1716188988.600805870] [atlas.scan_matching_odometry_component]: qos_overrides./tf.publisher.depth 100
[component_container_mt-4] [INFO] [1716188988.600809397] [atlas.scan_matching_odometry_component]: qos_overrides./tf.publisher.durability volatile
[component_container_mt-4] [INFO] [1716188988.600812909] [atlas.scan_matching_odometry_component]: qos_overrides./tf.publisher.history keep_last
[component_container_mt-4] [INFO] [1716188988.600816286] [atlas.scan_matching_odometry_component]: qos_overrides./tf.publisher.reliability reliable
[component_container_mt-4] [INFO] [1716188988.600819772] [atlas.scan_matching_odometry_component]: reg_correspondence_randomness 20
[component_container_mt-4] [INFO] [1716188988.600823471] [atlas.scan_matching_odometry_component]: reg_max_correspondence_distance 2.000000
[component_container_mt-4] [INFO] [1716188988.600826973] [atlas.scan_matching_odometry_component]: reg_max_optimizer_iterations 20
[component_container_mt-4] [INFO] [1716188988.600830798] [atlas.scan_matching_odometry_component]: reg_maximum_iterations       64
[component_container_mt-4] [INFO] [1716188988.600836871] [atlas.scan_matching_odometry_component]: reg_nn_search_method         DIRECT7
[component_container_mt-4] [INFO] [1716188988.600840572] [atlas.scan_matching_odometry_component]: reg_num_threads              0
[component_container_mt-4] [INFO] [1716188988.600844322] [atlas.scan_matching_odometry_component]: reg_resolution               1.000000
[component_container_mt-4] [INFO] [1716188988.600848268] [atlas.scan_matching_odometry_component]: reg_transformation_epsilon   0.100000
[component_container_mt-4] [INFO] [1716188988.600851760] [atlas.scan_matching_odometry_component]: reg_use_reciprocal_correspondences false
[component_container_mt-4] [INFO] [1716188988.600855297] [atlas.scan_matching_odometry_component]: registration_method          FAST_GICP
[component_container_mt-4] [INFO] [1716188988.600858804] [atlas.scan_matching_odometry_component]: result_dir                   
[component_container_mt-4] [INFO] [1716188988.600862400] [atlas.scan_matching_odometry_component]: robot_odom_frame_id          atlas/robot_odom
[component_container_mt-4] [INFO] [1716188988.600865873] [atlas.scan_matching_odometry_component]: transform_thresholding       false
[component_container_mt-4] [INFO] [1716188988.600869323] [atlas.scan_matching_odometry_component]: use_sim_time                 true
[component_container_mt-4] [INFO] [1716188988.603025834] [atlas.mrg_slam_container]: Load Library: /home/dong/3d_slam/Multi-Robot-Graph-SLAM/install/mrg_slam/lib/libmrg_slam_component.so
[component_container_mt-4] [INFO] [1716188988.635139651] [atlas.mrg_slam_container]: Found class: rclcpp_components::NodeFactoryTemplate<mrg_slam::MrgSlamComponent>
[component_container_mt-4] [INFO] [1716188988.635201689] [atlas.mrg_slam_container]: Instantiate class: rclcpp_components::NodeFactoryTemplate<mrg_slam::MrgSlamComponent>
[INFO] [launch_ros.actions.load_composable_nodes]: Loaded node '/atlas/mrg_slam_component' in container 'atlas/mrg_slam_container'
[component_container_mt-4] [INFO] [1716188991.772720827] [atlas.mrg_slam_component]: Initializing mrg_slam component...
[component_container_mt-4] construct solver: lm_var_cholmod
[component_container_mt-4] done
[component_container_mt-4] registration: FAST_GICP
[component_container_mt-4] [INFO] [1716188991.777628064] [atlas.mrg_slam_component]: Subscribing to odom topic /atlas/scan_matching_odometry/odom
[component_container_mt-4] [INFO] [1716188991.777655533] [atlas.mrg_slam_component]: Subscribing to cloud topic /atlas/prefiltering/filtered_points
[component_container_mt-4] [INFO] [1716188997.824445295] [atlas.mrg_slam_component]: accum_distance_thresh        25.000000
[component_container_mt-4] [INFO] [1716188997.824491134] [atlas.mrg_slam_component]: cloud_sub_topic              /filtered_points
[component_container_mt-4] [INFO] [1716188997.824502384] [atlas.mrg_slam_component]: const_stddev_q               0.100000
[component_container_mt-4] [INFO] [1716188997.824509986] [atlas.mrg_slam_component]: const_stddev_x               0.500000
[component_container_mt-4] [INFO] [1716188997.824517828] [atlas.mrg_slam_component]: distance_thresh              15.000000
[component_container_mt-4] [INFO] [1716188997.824531839] [atlas.mrg_slam_component]: enable_gps                   false
[component_container_mt-4] [INFO] [1716188997.824551934] [atlas.mrg_slam_component]: enable_imu_acceleration      false
[component_container_mt-4] [INFO] [1716188997.824558987] [atlas.mrg_slam_component]: enable_imu_orientation       false
[component_container_mt-4] [INFO] [1716188997.824564888] [atlas.mrg_slam_component]: fitness_score_max_range      inf
[component_container_mt-4] [INFO] [1716188997.824569652] [atlas.mrg_slam_component]: fitness_score_thresh         2.500000
[component_container_mt-4] [INFO] [1716188997.824573770] [atlas.mrg_slam_component]: fix_first_node               true
[component_container_mt-4] [INFO] [1716188997.824584118] [atlas.mrg_slam_component]: fix_first_node_adaptive      false
[component_container_mt-4] [INFO] [1716188997.824594824] [atlas.mrg_slam_component]: fix_first_node_stddev        [0.5, 0.5, 0.5, 0.0872665, 0.0872665, 0.0872665]
[component_container_mt-4] [INFO] [1716188997.824602952] [atlas.mrg_slam_component]: floor_edge_robust_kernel     NONE
[component_container_mt-4] [INFO] [1716188997.824609743] [atlas.mrg_slam_component]: floor_edge_robust_kernel_size 1.000000
[component_container_mt-4] [INFO] [1716188997.824614188] [atlas.mrg_slam_component]: floor_edge_stddev            10.000000
[component_container_mt-4] [INFO] [1716188997.824618765] [atlas.mrg_slam_component]: g2o_solver_num_iterations    512
[component_container_mt-4] [INFO] [1716188997.824629530] [atlas.mrg_slam_component]: g2o_solver_type              lm_var_cholmod
[component_container_mt-4] [INFO] [1716188997.824640822] [atlas.mrg_slam_component]: g2o_verbose                  false
[component_container_mt-4] [INFO] [1716188997.824645127] [atlas.mrg_slam_component]: gps_edge_robust_kernel       NONE
[component_container_mt-4] [INFO] [1716188997.824649406] [atlas.mrg_slam_component]: gps_edge_robust_kernel_size  1.000000
[component_container_mt-4] [INFO] [1716188997.824658072] [atlas.mrg_slam_component]: gps_edge_stddev_xy           20.000000
[component_container_mt-4] [INFO] [1716188997.824662589] [atlas.mrg_slam_component]: gps_edge_stddev_z            5.000000
[component_container_mt-4] [INFO] [1716188997.824670072] [atlas.mrg_slam_component]: gps_time_offset              0.000000
[component_container_mt-4] [INFO] [1716188997.824674341] [atlas.mrg_slam_component]: graph_exchange_mode          PATH_PROXIMITY
[component_container_mt-4] [INFO] [1716188997.824678618] [atlas.mrg_slam_component]: graph_request_max_robot_dist 50.000000
[component_container_mt-4] [INFO] [1716188997.824682585] [atlas.mrg_slam_component]: graph_request_min_accum_dist 2.000000
[component_container_mt-4] [INFO] [1716188997.824693141] [atlas.mrg_slam_component]: graph_request_min_time_delay 2.000000
[component_container_mt-4] [INFO] [1716188997.824697499] [atlas.mrg_slam_component]: graph_update_interval        3.000000
[component_container_mt-4] [INFO] [1716188997.824701243] [atlas.mrg_slam_component]: imu_acceleration_edge_robust_kernel NONE
[component_container_mt-4] [INFO] [1716188997.824707785] [atlas.mrg_slam_component]: imu_acceleration_edge_robust_kernel_size 1.000000
[component_container_mt-4] [INFO] [1716188997.824712826] [atlas.mrg_slam_component]: imu_acceleration_edge_stddev 1.000000
[component_container_mt-4] [INFO] [1716188997.824716639] [atlas.mrg_slam_component]: imu_orientation_edge_robust_kernel NONE
[component_container_mt-4] [INFO] [1716188997.824724048] [atlas.mrg_slam_component]: imu_orientation_edge_robust_kernel_size 1.000000
[component_container_mt-4] [INFO] [1716188997.824732184] [atlas.mrg_slam_component]: imu_orientation_edge_stddev  1.000000
[component_container_mt-4] [INFO] [1716188997.824736621] [atlas.mrg_slam_component]: imu_time_offset              0.000000
[component_container_mt-4] [INFO] [1716188997.824749374] [atlas.mrg_slam_component]: init_pose                    [0, 0, 0, 0, 0, 0]
[component_container_mt-4] [INFO] [1716188997.824753666] [atlas.mrg_slam_component]: init_pose_topic              NONE
[component_container_mt-4] [INFO] [1716188997.824757714] [atlas.mrg_slam_component]: keyframe_delta_angle         1.000000
[component_container_mt-4] [INFO] [1716188997.824765485] [atlas.mrg_slam_component]: keyframe_delta_trans         1.000000
[component_container_mt-4] [INFO] [1716188997.824787141] [atlas.mrg_slam_component]: loop_closure_consistency_max_delta_angle 3.000000
[component_container_mt-4] [INFO] [1716188997.824792628] [atlas.mrg_slam_component]: loop_closure_consistency_max_delta_trans 0.300000
[component_container_mt-4] [INFO] [1716188997.824802623] [atlas.mrg_slam_component]: loop_closure_edge_robust_kernel Huber
[component_container_mt-4] [INFO] [1716188997.824806889] [atlas.mrg_slam_component]: loop_closure_edge_robust_kernel_size 1.000000
[component_container_mt-4] [INFO] [1716188997.824810769] [atlas.mrg_slam_component]: map_cloud_count_threshold    2
[component_container_mt-4] [INFO] [1716188997.824818178] [atlas.mrg_slam_component]: map_cloud_resolution         0.100000
[component_container_mt-4] [INFO] [1716188997.824825087] [atlas.mrg_slam_component]: map_cloud_update_interval    2.000000
[component_container_mt-4] [INFO] [1716188997.824829123] [atlas.mrg_slam_component]: map_frame_id                 atlas/map
[component_container_mt-4] [INFO] [1716188997.824832981] [atlas.mrg_slam_component]: max_keyframes_per_update     10000
[component_container_mt-4] [INFO] [1716188997.824839419] [atlas.mrg_slam_component]: max_stddev_q                 0.200000
[component_container_mt-4] [INFO] [1716188997.824844191] [atlas.mrg_slam_component]: max_stddev_x                 5.000000
[component_container_mt-4] [INFO] [1716188997.824860421] [atlas.mrg_slam_component]: min_edge_interval            15.000000
[component_container_mt-4] [INFO] [1716188997.824864913] [atlas.mrg_slam_component]: min_stddev_q                 0.050000
[component_container_mt-4] [INFO] [1716188997.824871459] [atlas.mrg_slam_component]: min_stddev_x                 0.100000
[component_container_mt-4] [INFO] [1716188997.824878370] [atlas.mrg_slam_component]: model_namespace              atlas
[component_container_mt-4] [INFO] [1716188997.824883216] [atlas.mrg_slam_component]: multi_robot_names            [atlas, bestla]
[component_container_mt-4] [INFO] [1716188997.824886991] [atlas.mrg_slam_component]: odom_frame_id                atlas/odom
[component_container_mt-4] [INFO] [1716188997.824893012] [atlas.mrg_slam_component]: odom_sub_topic               /odom
[component_container_mt-4] [INFO] [1716188997.824897898] [atlas.mrg_slam_component]: odometry_edge_robust_kernel  NONE
[component_container_mt-4] [INFO] [1716188997.824902394] [atlas.mrg_slam_component]: odometry_edge_robust_kernel_size 1.000000
[component_container_mt-4] [INFO] [1716188997.824912548] [atlas.mrg_slam_component]: own_name                     atlas
[component_container_mt-4] [INFO] [1716188997.824916416] [atlas.mrg_slam_component]: points_topic                 /velodyne_points
[component_container_mt-4] [INFO] [1716188997.824920193] [atlas.mrg_slam_component]: qos_overrides./clock.subscription.depth 1
[component_container_mt-4] [INFO] [1716188997.824926978] [atlas.mrg_slam_component]: qos_overrides./clock.subscription.durability volatile
[component_container_mt-4] [INFO] [1716188997.824931322] [atlas.mrg_slam_component]: qos_overrides./clock.subscription.history keep_last
[component_container_mt-4] [INFO] [1716188997.824935084] [atlas.mrg_slam_component]: qos_overrides./clock.subscription.reliability best_effort
[component_container_mt-4] [INFO] [1716188997.824942457] [atlas.mrg_slam_component]: qos_overrides./parameter_events.publisher.depth 1000
[component_container_mt-4] [INFO] [1716188997.824947155] [atlas.mrg_slam_component]: qos_overrides./parameter_events.publisher.durability volatile
[component_container_mt-4] [INFO] [1716188997.824954170] [atlas.mrg_slam_component]: qos_overrides./parameter_events.publisher.history keep_last
[component_container_mt-4] [INFO] [1716188997.824964304] [atlas.mrg_slam_component]: qos_overrides./parameter_events.publisher.reliability reliable
[component_container_mt-4] [INFO] [1716188997.824968989] [atlas.mrg_slam_component]: reg_correspondence_randomness 20
[component_container_mt-4] [INFO] [1716188997.824973110] [atlas.mrg_slam_component]: reg_max_correspondence_distance 2.000000
[component_container_mt-4] [INFO] [1716188997.824979231] [atlas.mrg_slam_component]: reg_max_optimizer_iterations 20
[component_container_mt-4] [INFO] [1716188997.824984341] [atlas.mrg_slam_component]: reg_maximum_iterations       64
[component_container_mt-4] [INFO] [1716188997.824988343] [atlas.mrg_slam_component]: reg_nn_search_method         DIRECT7
[component_container_mt-4] [INFO] [1716188997.824995078] [atlas.mrg_slam_component]: reg_num_threads              0
[component_container_mt-4] [INFO] [1716188997.824999546] [atlas.mrg_slam_component]: reg_resolution               1.000000
[component_container_mt-4] [INFO] [1716188997.825003690] [atlas.mrg_slam_component]: reg_transformation_epsilon   0.100000
[component_container_mt-4] [INFO] [1716188997.825007478] [atlas.mrg_slam_component]: reg_use_reciprocal_correspondences false
[component_container_mt-4] [INFO] [1716188997.825013428] [atlas.mrg_slam_component]: registration_method          FAST_GICP
[component_container_mt-4] [INFO] [1716188997.825018508] [atlas.mrg_slam_component]: result_dir                   
[component_container_mt-4] [INFO] [1716188997.825026130] [atlas.mrg_slam_component]: robot_remove_points_radius   2.000000
[component_container_mt-4] [INFO] [1716188997.825030399] [atlas.mrg_slam_component]: save_graph                   false
[component_container_mt-4] [INFO] [1716188997.825034225] [atlas.mrg_slam_component]: use_const_inf_matrix         false
[component_container_mt-4] [INFO] [1716188997.825041224] [atlas.mrg_slam_component]: use_loop_closure_consistency_check true
[component_container_mt-4] [INFO] [1716188997.825045060] [atlas.mrg_slam_component]: use_planar_registration_guess false
[component_container_mt-4] [INFO] [1716188997.825048768] [atlas.mrg_slam_component]: use_sim_time                 true
[component_container_mt-4] [INFO] [1716188997.825052896] [atlas.mrg_slam_component]: var_gain_a                   20.000000

**Comment by DongDong-Juice** [comment]
mrg_slam.launch.py 
def launch_setup(context, *args, **kwargs):

    config_file = 'mrg_slam_velodyne_VLP16.yaml'
    
Solved with modification.
thank you

**Comment by aserbremen** [comment]
you can actually supply the config with your launch command:

`ros2 launch mrg_slam mrg_slam.launch.py config:=mrg_slam_velodyne_VLP16.yaml model_namespace:=atlas x:=0.0 y:=0.0 z:=0.0 roll:=0.0 pitch:=0.0 yaw:=0.0
`

as long as the config is in the `config` folder of the `mrg_slam` package. if you add a new config you just have to rebuild the package

**Comment by aserbremen** [comment]
I have added that information to the readme
