### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by DongDong-Juice** [aserbremen/Multi-Robot-Graph-SLAM#3]
hello @aserbremen 
There were no problems with the previous build, but today, I am informing you that a grammar problem occurred while deleting the build and attempting a new build. If you correct the part where the error occurs and build, there will be no problem using it, but please check.

/home/dong/3d_slam/src/Multi-Robot-Graph-SLAM/src/mrg_slam/apps/mrg_slam_component.cpp: In member function ‘void mrg_slam::MrgSlamComponent::save_map_service(mrg_slam_msgs::srv::SaveMap_Request_<std::allocator<void> >::ConstSharedPtr, mrg_slam_msgs::srv::SaveMap_Response_<std::allocator<void> >::SharedPtr)’:
/home/dong/3d_slam/src/Multi-Robot-Graph-SLAM/src/mrg_slam/apps/mrg_slam_component.cpp:1466:56: error: ‘zekhro_utm’ was not declared in this scope; did you mean ‘zero_utm’?
 ofs << boost::format( "%.6f %.6f %.6f" ) % zekhro_utm->x() % zero_utm->y() % zero_utm->z() << std::endl;
                                                                     ^~~~~~~~~~
                                                                   zero_utm

zekhro_utm -> zero_utm

**Comment by aserbremen** [comment]
I am not sure where this error is coming from. which branch are you using? because on the `main` branch I don't find this typo

**Comment by DongDong-Juice** [comment]
Well... this happened when I first performed a git pull operation today and built it using the colcon build command.

**Comment by DongDong-Juice** [comment]
It's a different story, but I used turtlebot4 
You are using ROS_DISCOVER_SERVER to communicate your SLAM topics. However, sometimes the connection of velodyne Lidar is unstable and a problem occurs where it sticks on and off... In the case of velodyne, it is communicating with my PC through WIFI through a router. Is this the problem?... 
I'm curious what you think...!

**Comment by aserbremen** [comment]
Inside your ROS2 colcon workspace you can `vcs pull src` to update all repositories
